name: Publish to Docs

on:
  push:
    branches: [ test ] # Change to main after mainnet is live and we publish masa-oracle to main (if desired)
    paths: 
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v4
      - name: Copy Readme
        run: |
            mkdir pub-docs
            cp -r docs/welcome-to-masa pub-docs/
            cp -r docs/ai-worker-node pub-docs/
            cp -r docs/ai-oracle-node pub-docs/
            cp -r docs/guides-and-tutorials pub-docs/
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'pub-docs'
          target-directory: 'docs/masa-oracle'
          destination-github-username: 'masa-finance'
          destination-repository-name: 'docs'
          user-email: 13647606+H34D@users.noreply.github.com
          target-branch: main